# Generated by Django 6.1.1 on 2026-09-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TituloAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], max_length=3, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(db_index=True, max_length=20, verbose_name='Número de Documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('carrera', models.CharField(max_length=150, verbose_name='Carrera / Programa Académico')),
                ('seccional', models.CharField(help_text='Ej: Sede Fusagasugá, Seccional Girardot, Extensión Ubaté, etc.', max_length=100, verbose_name='Seccional / Sede')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_grado', models.DateField(verbose_name='Fecha de Graduación / Salida')),
                ('hash_bloque', models.CharField(blank=True, help_text='Hash criptográfico inmutable que identifica el título en la cadena de bloques.', max_length=64, unique=True, verbose_name='Hash del Bloque Blockchain')),
                ('hash_anterior', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash del Bloque Anterior')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Título Académico',
                'verbose_name_plural': 'Títulos Académicos',
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
    ]
