# Generated by Django 6.1.1 on 2026-09-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tituloacademico',
            name='hash_bloque',
            field=models.CharField(blank=True, help_text='Hash criptográfico inmutable que identifica el título en la cadena de bloques.', max_length=64, unique=True, verbose_name='Hash del Bloque Blockchain'),
        ),
    ]
