# Generated by Django 4.1.2 on 2023-10-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADMIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=15)),
                ('Contrasena', models.CharField(max_length=30)),
                ('NombreAd', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDent', models.CharField(max_length=40)),
                ('Nombre', models.CharField(max_length=40)),
                ('Carrera', models.CharField(max_length=20)),
            ],
        ),
    ]
