# Generated by Django 4.1.2 on 2026-05-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Contrasena',
            field=models.CharField(max_length=128),
        ),
    ]
